// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230330194546_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminStatu")
                        .HasColumnType("int");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Departman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<byte>("BarkodKod36")
                        .HasColumnType("tinyint");

                    b.Property<string>("ModelAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Musteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("QR")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("TerminTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ulke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yikamasi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EntityLayer.Concrete.StatuKategori", b =>
                {
                    b.Property<int>("StatuKategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("StatuKategoriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatuKategoriId");

                    b.ToTable("StatuKategorileri");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Surec", b =>
                {
                    b.Property<int>("SurecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaslangicDurum")
                        .HasColumnType("int");

                    b.Property<int>("BitisDurum")
                        .HasColumnType("int");

                    b.Property<string>("CihazAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosyaDevamEdenler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HataMesaji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("StatuKategoriId")
                        .HasColumnType("int");

                    b.Property<int>("SurecKategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih2")
                        .HasColumnType("datetime2");

                    b.HasKey("SurecId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StatuKategoriId");

                    b.HasIndex("SurecKategoriId");

                    b.ToTable("Surecler");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SurecKategori", b =>
                {
                    b.Property<int>("SurecKategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("SurecKategoriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SurecKategoriId");

                    b.ToTable("SurecKategorileri");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Surec", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Kullanici", "Kullanici")
                        .WithMany("Surecs")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Order", "Order")
                        .WithMany("Surecs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.StatuKategori", "StatuKategori")
                        .WithMany("Surecs")
                        .HasForeignKey("StatuKategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.SurecKategori", "SurecKategori")
                        .WithMany("Surecs")
                        .HasForeignKey("SurecKategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Order");

                    b.Navigation("StatuKategori");

                    b.Navigation("SurecKategori");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Kullanici", b =>
                {
                    b.Navigation("Surecs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Order", b =>
                {
                    b.Navigation("Surecs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.StatuKategori", b =>
                {
                    b.Navigation("Surecs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SurecKategori", b =>
                {
                    b.Navigation("Surecs");
                });
#pragma warning restore 612, 618
        }
    }
}
